export const ApiPathConfig = {
  auth: {
    login: '/oauth/token',
    detailUser: '/oauth/user_login',
    logOut: '/oauth/logout',
    changePassword: '/oauth/change-pass',
    forgotPassword: '/oauth/forget-password',
    otherLogin: '/oauth/another-user',
    sendOtp: '/oauth/otp/request',
    verifyOtp: '/oauth/otp/verification',
    registerExporter: '/api/exporter',
    registerUser: '/oauth/customer',
    checkExistUser: '/oauth/check-exist-account',
    checkExistPhone: '/oauth/check-exist-phone',
    emailUs: '/oauth/email-us',
    country: '/oauth/common/country',
    profile: '/oauth/profile',
    activated: '/oauth/activated',
    listBuyer: '/api/buyer',
    listSeller: '/api/admin/seller',
    changePhone: '/oauth/change-phone',
    changeMail: '/oauth/change-mail',
    sendLinkVertification: '/oauth/send-link-vertification',
    activatedAccount: '/oauth/activated-account',
    activatedExpoxter: '/oauth/activated-expoxter'
  },

  service: {
    dialogSeach: {
      dialogCommon: '/api/common/dialog-common',
      getProductBySet: '/api/product-by-set',
      getProductChild: '/api/product-child'
    },
    pdfUpload: '/api/user/pdf'
  },
  user: {
    user: '/api/user',
    sendMail: '/api/user/send-mail',
    exportCSV: '/api/user/downloadCSV',
    changePassword: '/api/user/change-pass'
  },
  common: {
    zipcode: '/api/common/zip-code',
    checkPhone: '/api/verifi-phone',
    banks: '/api/common/bank',
    chat: '/api/common/chat',
    getAddress: '/api/address'
  },
  system: {
    user: '/api/user/system',
    userCsv: '/api/system/downloadCSV',
    productCategory: '/api/category'
  },
  customer: {
    customer: '/api/customer',
    avatar: '/api/customer/avatar',
    password: '/api/customer/password',
    address: '/api/customer/address',
    phone: '/api/customer/phone',
    email: '/api/customer/email',
    name: '/api/customer/name',
    verifyOtp: '/api/otp/verification',
    country: '/api/country',
    lockAccount: '/api/customer/lock-account',
    checkEmailCustomer: '/api/customer/verifi-email',
    create: '/oauth/customer/create'
  },
  exporter: {
    exporter: '/api/exporter/create',
    avatar: '/api/exporter/avatar',
    password: '/api/exporter/password',
    address1: '/api/exporter/address1',
    address2: '/api/exporter/address2',
    phone: '/api/exporter/phone',
    email: '/api/exporter/email',
    name: '/api/exporter/name',
    verifyOtp: '/api/otp/verification',
    country: '/api/country',
    checkEmailExporter: '/api/exporter/verifi-email',
    order: '/api/exporter/order',
    checkPhoneCompany: '/api/exporter/check-phone-company',
    checkPhoneRepresentative: '/api/exporter/check-phone-representative',
    lockAccount: '/api/exporter/lock-account',
    getProduct: '/api/exporter/product',
    getPitch: '/api/getListPitch',
    deletePromotion: '/api/seller/deletePromotion',
    createPromotion: '/api/seller/addPromotion',
    updatePromotion: '/api/seller/updatePromotion',
    getAllPromotion: '/api/promotion',
    deleteProduct: '/api/seller/deleteProduct',
    createProduct: '/api/seller/addProduct',
    updateProduct: '/api/seller/updateProduct',
    getListCategory: '/api/getListCategory',
    getListCategoryPitch: '/api/getListCategoryPitch',
    getListTime: '/api/getTime',
    getAllPitch: '/api/getAllPitch',
    getProductByCategory: '/api/getListProductByCategory',
    addComment: '/api/user/addComment',
    getComment: '/api/getcomment',
    addCart: '/api/operator/addCart',
    getListCart: '/api/getListCart',
    deleteCart: '/api/seller/deleteCart',
    addOrder: '/api/addOrder',
    addHistory: '/api/addHistory',
    sellerGetOrder: '/api/seller/getOrder',
    confirmOrder: '/api/seller/confirmOrder',
    buyerGetOrder: '/api/buyer/getOrder',
    deleteOrder: '/api/seller/deleteOrder',
    addPitch: '/api/seller/addPitch',
    adminGetOrder: '/api/admin/getOrder'
  },
  operator: {
    operator: '/api/operator/create',
    getById: '/api/operator',
    getAll: '/api/operator/system',
    checkExistUser: '/oauth/check-exist-account',
    deleteByid: '/api/operator/delete',
    updateOperator: '/api/operator/update',
    daleteList: '/api/operator/deleteList',
    resetPass: '/api/operator/reset',
    category: '/api/operator/category',
    categorySp: '/api/operator/categorySp',
    categorySb: '/api/operator/categorySb',
    getAllCategory: '/api/operator/getCategory',
    order: '/api/operator/order',
    remittanceList: '/api/operator/remittance',
    updateStatusConfirm: '/api/operator/status-confirm',
    deleteCategory: '/api/operator/deleteCategory',
    addCategory: '/api/operator/addCategory',
    updateCategory: '/api/operator/updateCategory',
    activeCategory: '/api/operator/activeCategory',
    getAllNews: '/api/operator/news',
    deleteNews: '/api/operator/deleteNews',
    createNew: '/api/operator/addNews',
    updateNews: '/api/operator/updateNews',
    activeNews: '/api/operator/activeNews',
    getPost: '/api/operator/post',
    checkLogin: '/api/common/checklogin'

  },
  order: {
    createOrder: "/api/operator/create-order",
    checkEmail: "/api/check-mail",
    daleteList: '/api/operator/deleteList',
    deleteOrder: '/api/delete/orderoperator',
    updateOrderOperator: '/api/operator/update-order',
    confirmBlOperator: '/api/operator/confirm-bl'

  },
  orderCustomer: {
    getAll: '/api/customer/order',
    deleteByid: '/api/order/delete'
  }
};
